services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    command: ["node", "dist/server.js"]
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      PORT: 3000

      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}

      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GEMINI_EMBEDDING_MODEL: ${GEMINI_EMBEDDING_MODEL}
      GEMINI_EMBEDDING_DIMENSIONS: ${GEMINI_EMBEDDING_DIMENSIONS}

      RESEND_API_KEY: ${RESEND_API_KEY}
      EMAIL_FROM: ${EMAIL_FROM}

      REDIS_URL: redis://redis:6379

      CORS_ORIGIN: ${CORS_ORIGIN}
    
    depends_on:
      redis:
        condition: service_healthy
  
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["node", "dist/workers/enrichment.worker.js"]
    restart: unless-stopped
    environment:
      NODE_ENV: production

      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}

      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GEMINI_EMBEDDING_MODEL: ${GEMINI_EMBEDDING_MODEL}
      GEMINI_EMBEDDING_DIMENSIONS: ${GEMINI_EMBEDDING_DIMENSIONS}

      RESEND_API_KEY: ${RESEND_API_KEY}
      EMAIL_FROM: ${EMAIL_FROM}

    depends_on:
      redis:
        condition: service_healthy
  

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  redis_data: